CCDNMessage\MessageBundle\Entity\Envelope:
    type: entity
    table: cc_message_envelope
    repositoryClass: CCDNMessage\MessageBundle\Repository\EnvelopeRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        isDraft:
            type: boolean
            column: is_draft
            nullable: false
        isRead:
            type: boolean
            column: is_read
            nullable: false
        isFlagged:
            type: boolean
            column: is_flagged
            nullable: false
        sentDate:
            type: datetime
            column: sent_date
            nullable: true
    manyToOne:
        folder:
            targetEntity: CCDNMessage\MessageBundle\Entity\Folder
            inversedBy: envelopes
            cascade: ["persist"]
            joinColumn:
                name: fk_folder_id
                referencedColumnName: id
                onDelete: SET NULL
        message:
            targetEntity: CCDNMessage\MessageBundle\Entity\Message
            inversedBy: envelopes
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_message_id
                referencedColumnName: id
                onDelete: SET NULL
        thread:
            targetEntity: CCDNMessage\MessageBundle\Entity\Thread
            inversedBy: envelopes
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_thread_id
                referencedColumnName: id
                onDelete: SET NULL
        ownedByUser:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
