CCDNMessage\MessageBundle\Entity\Folder:
    type: entity
    table: cc_message_folder
    repositoryClass: CCDNMessage\MessageBundle\Repository\FolderRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        specialType:
            type: integer
            column: special_type
            nullable: true
        cachedReadCount:
            type: integer
            column: cached_read_count
            nullable: true
        cachedUnreadCount:
            type: integer
            column: cached_unread_count
            nullable: true
        cachedTotalMessageCount:
            type: integer
            column: cached_total_message_count
            nullable: true
    manyToOne:
        ownedBy:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: ["persist"]
            nullable: true
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
