
CCDNMessageMessageBundle-User-Folder:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing/user-folder.yml"
    prefix: /{_locale}/messages

CCDNMessageMessageBundle-User-Message:
    resource: "@CCDNMessageMessageBundle/Resources/config/routing/user-message.yml"
    prefix: /{_locale}/messages

